from typing import Dict, List
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from datetime import datetime
from app.llm import get_llm


llm = get_llm(temperature=0)

def generate_comprehensive_notes(
    session_topic: str,
    checkpoints: List[Dict],
    weak_areas: List[str] = None
) -> str:
    
    system_msg = SystemMessage(content="""You are an expert study notes creator.

Create comprehensive, well-structured study notes with:
- Clear section organization
- Key concepts highlighted
- Memory aids and mnemonics
- Review questions
- Practical applications

Use markdown formatting for structure.""")
    
    checkpoints_text = "\n".join([
        f"{i+1}. {cp.get('topic')} (Level: {cp.get('level', 'intermediate')})"
        for i, cp in enumerate(checkpoints)
    ])
    
    weak_areas_text = "\n".join(f"- {area}" for area in (weak_areas or []))
    
    human_msg = HumanMessage(content=f"""Create comprehensive study notes for:

MAIN TOPIC: {session_topic}

COVERED CHECKPOINTS:
{checkpoints_text}

WEAK AREAS (if any):
{weak_areas_text if weak_areas else "None identified"}

Create detailed notes with:
1. Table of contents
2. Summary of each checkpoint
3. Key concepts and definitions
4. Memory aids and mnemonics
5. Practice questions
6. Study tips
7. Next steps

Format: Markdown with clear headers and structure.""")
    
    response = llm.invoke([system_msg, human_msg])
    
    notes = f"""# Complete Learning Notes: {session_topic}

**Generated:** {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
**Total Checkpoints:** {len(checkpoints)}

---

{response.content}

---

## 📌 Study Tips for Mastery

1. **Spaced Repetition**: Review these notes at increasing intervals
   - Day 1: After completion
   - Day 3: First review
   - Week 1: Second review
   - Week 2: Third review
   - Month 1: Long-term retention check

2. **Active Recall**: Test yourself without looking at notes
   - Cover sections and try to remember
   - Explain concepts out loud
   - Teach someone else

3. **Feynman Technique**: Simplify and explain
   - Explain in simple words
   - Identify gaps in understanding
   - Review and simplify further

4. **Practice Application**: Use what you learned
   - Work on real projects
   - Solve related problems
   - Build something practical

5. **Community Engagement**: Learn with others
   - Join online forums
   - Participate in discussions
   - Share your knowledge

## 🎯 Action Items

- [ ] Review all checkpoints systematically
- [ ] Complete all practice questions
- [ ] Build a project using {session_topic}
- [ ] Teach these concepts to someone
- [ ] Explore advanced topics

---

*Generated by Conceptly - Your AI Learning Companion*
*Keep learning, keep growing! 🌱*
"""
    
    return notes

def generate_cheat_sheet(
    session_topic: str,
    checkpoints: List[Dict]
) -> str:
    
    system_msg = SystemMessage(content="""Create a concise cheat sheet.

Include:
- Key concepts only
- Quick reference format
- Bullet points and lists
- No lengthy explanations
- Easy to scan

Keep it under 500 words.""")
    
    checkpoints_text = "\n".join([
        f"- {cp.get('topic')}: {', '.join(cp.get('key_concepts', [])[:3])}"
        for cp in checkpoints
    ])
    
    human_msg = HumanMessage(content=f"""Create quick reference cheat sheet for:

TOPIC: {session_topic}

CHECKPOINTS:
{checkpoints_text}

Format: Markdown with clear sections and bullet points.""")
    
    response = llm.invoke([system_msg, human_msg])
    
    return f"""# {session_topic} - Quick Reference

**Generated:** {datetime.now().strftime("%B %d, %Y")}

---

{response.content}

---

*Quick reference only - Review full notes for details*
"""

def generate_practice_questions(
    session_topic: str,
    checkpoints: List[Dict]
) -> str:
    
    system_msg = SystemMessage(content="""Generate practice questions for review.

Create:
- Multiple types of questions (MCQ, short answer, conceptual)
- Range of difficulty levels
- Cover all major topics
- Include answer key hints

Format: Clear question numbering with space for answers.""")
    
    checkpoints_text = "\n".join([
        f"{i+1}. {cp.get('topic')}: {', '.join(cp.get('objectives', [])[:2])}"
        for i, cp in enumerate(checkpoints)
    ])
    
    human_msg = HumanMessage(content=f"""Generate comprehensive practice questions for:

TOPIC: {session_topic}

CHECKPOINTS:
{checkpoints_text}

Create at least 2-3 questions per checkpoint covering key concepts.""")
    
    response = llm.invoke([system_msg, human_msg])
    
    return f"""# {session_topic} - Practice Questions

**Generated:** {datetime.now().strftime("%B %d, %Y")}

Test your understanding with these practice questions!

---

{response.content}

---

## 💡 How to Use These Questions

1. **Initial Test**: Try answering without notes
2. **Review**: Check your answers against materials
3. **Identify Gaps**: Note areas needing more study
4. **Repeat**: Retest yourself after studying
5. **Track Progress**: Monitor improvement over time

---

*Practice makes perfect! Keep testing yourself! 🎯*
"""